export const NavBarLeftTitle = `Deposit.Finance`;
export const NavBarButtonLeft = `App`;

export const headingP1 = `Enjoy Defi`;
export const headingP2 = `With Ease`;

export const introTitle = `| About Deposit.Finance`;
export const intro = (
  <span className="text-secondary-white text-3xl"><span className="text-white font-extrabold">Have you</span> ever wanted to become an owner of an investment fund ? 
   We are here to bring you safe, wide and automatised defi exposure to institutional investors 
   We will let differents actors invest in our treasury in an innovative and easy way 
  <br/>

   <span className="text-white font-extrabold">This treasury</span> will be deployed on different blockchain investing in different projects that have a positive cashflow, 
   the yield gained will be will be redistributed to investors, governance token holder and reinvested to grow our treasury
   <br/><br/>


   <span className="text-white font-extrabold">Before launch</span> of our final product, all yield generated by the treasury will be distributed to our governance token holders 
   </span>
)

export const card1SubTitle = `| Whats new?`
export const card1Title = `Launch of our Governance Token`
export const card1AnimatedImage = '/whats-new.png'
export const card1News = [
  {
    imgUrl: '/vrpano.svg',
    title: 'Fair Token Distribution',
    subtitle:
        `DEEPFI holders will receive a part of all revenue generated per or final product and have a word in the say of where the treasury is deployed. `,
  },
  {
    imgUrl: '/headset.svg',
    title: '... With Advantage',
    subtitle:
        `All our DEEPFI will have distributed before the launch of our final product`,
  },
];

export const card2SubTitle = `| How it Works`
export const card2Title = `Three Ways To Get An Hand On It`
export const card2SubTitle2 = `Any remaining DEEFI will be airdroped to holders`
export const card2AnimatedImage = '/get-started.png'
export const card2StartingFeatures = [
    `We will offer bonds where you will be able to get DEEPFI at a discount and will permit us to create liquidity and bootstrap our treasury`,
    `We will incentive people to participate in our liquidity by distributing treasury yield and and DEEPFI token to it`,
    `We will offer our token in a few stacking pool where you can deposit the cryptos you like and farm DEEPFI`,
];

export const roadMapTitle = `What's Next ?`
export const roadMapSubTitle = `Road Map`
export const roadMapTexte = `[WIP]`


export const footerTitle = 'Enter the DeFi'
export const footerButton = 'Explore'
export const footerSubTitle = 'Deposit.Finance'
export const footerCopyrights = 'Copyright © 2021 - 2023 Deposit.Finance. All rights reserved.'
export const footerSocials = [
  {
    name: 'twitter',
    url:'/',
    imageUrl: '/twitter.svg',
  },
  {
    name: 'linkedin',
    url:'/',
    imageUrl: '/linkedin.svg',
  },
  {
    name: 'instagram',
    url:'/',
    imageUrl: '/instagram.svg',
  },
  {
    name: 'facebook',
    url:'/',
    imageUrl: '/facebook.svg',
  },
];






  
  export const insights = [
    {
      imgUrl: '/planet-06.png',
      title: 'The launch of the Metaverse makes Elon musk ketar-ketir',
      subtitle:
          'Magna etiam tempor orci eu lobortis elementum nibh tellus molestie. Diam maecenas sed enim ut sem viverra alique.',
    },
    {
      imgUrl: '/planet-07.png',
      title: '7 tips to easily master the madness of the Metaverse',
      subtitle:
          'Vitae congue eu consequat ac felis donec. Et magnis dis parturient montes nascetur ridiculus mus. Convallis tellus id interdum',
    },
    {
      imgUrl: '/planet-08.png',
      title: 'With one platform you can explore the whole world virtually',
      subtitle:
          'Quam quisque id diam vel quam elementum. Viverra nam libero justo laoreet sit amet cursus sit. Mauris in aliquam sem',
    },
  ];
  
