'use client';

import { motion } from 'framer-motion';
import { TypingText } from '../../components/home';

import styles from '../../styles';
import { fadeIn, staggerContainer } from '../../utils/motion';
import { intro, introTitle } from '../../constants/HomePage_Texts';

const About = () => (
  <section className={`${styles.paddings} relative z-10 sm:-mt-10`}>
    <div className="gradient-02 z-0" />
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      whileInView="show"
      viewport={{ once: false, amount: 0.25 }}
      className={`${styles.innerWidth} mx-auto ${styles.flexCenter} flex-col`}
    >
      <TypingText title={introTitle} textStyles="text-center" />

      <motion.p
        variants={fadeIn('up', 'tween', 0.2, 1)}
        className="mt-[8px] font-normal sm:text-[32px] text-[20px] text-center"
      >
        {/* <span className="font-extrabold text-white">Have you</span> ever wanted to become an owner of an investment fund ? We are here for you
Bring safe, wide and automatised defi exposure to institutional investors
We will let differents actors invest in our treasury in an innovative and easy way <br /><br />{' '}
        <span className="font-extrabold text-white">
        This treasury
        </span>{' '}
        will be deployed on different blockchain investing in different projects that have a positive cashflow, {' '}
        <span className="font-extrabold text-white">the yield</span> gained will be will be redistributed to investors, governance token holder and reinvested to grow our treasury<br /><br />{' '}
        <span className="font-extrabold text-white">Before launch</span> of or final product, all yield generated by the treasury will be distributed to our governance token holders */}
              <span className=" text-white">{intro}</span>
      </motion.p>


      <motion.img
        variants={fadeIn('up', 'tween', 0.3, 1)}
        src="/arrow-down.svg"
        alt="arrow down"
        className="w-[18px] h-[28px] object-contain mt-[28px]"
      />
    </motion.div>
  </section>
);

export default About;
