import TreasuryRenderer from 'components/app/TreasuryRenderer'
import UserMetricsRenderer from 'components/app/UserMetricsRenderer'
import Loader from "components/app/Loader";

import { motion } from 'framer-motion';

import styles from 'styles';
import { slideIn, staggerContainer, textVariant } from 'utils/motion';

const VaultMetrics = ({ treasury, userMetrics }) => {
  return (
    <>
      <section className='sm:pt-8 sm:pb-20 py-12'>

        <motion.div
          variants={staggerContainer}
          initial="hidden"
          whileInView="show"
          viewport={{ once: false, amount: 0.25 }}
          className={`${styles.innerWidth} mx-auto flex flex-col`}
        >
          <div className='flex flex-col w-auto '>
            <div className="flex h-4/5 w-auto items-center">
              <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                <motion.div
                  variants={slideIn('left', 'tween', 0.1, 0.75)}
                  className="overflow-hidden rounded-3xl bg-purple-500/10 shadow-xl lg:grid lg:grid-cols-2 lg:gap-4"

                >
                  <div className="px-6 pt-10 pb-12 sm:px-16 sm:pt-16 lg:py-16 lg:pr-0 xl:py-20 xl:px-20">
                    <div className="lg:self-center ">
                      <h2 className="text-3xl font-bold tracking-tight text-white">
                        <span className="block">Protocol</span>
                      </h2>
                      <p className="mt-4 text-lg leading-6 text-indigo-200">
                      liquidity generated by all strategies
                      </p>

                      <TreasuryRenderer treasury={treasury} />
                    </div>
                  </div>
                  <div className="mb-8">


                    <div className="flex justify-center items-center pt-8 text-md">
                      <motion.div
                        variants={slideIn('right', 'tween', 0.7, 0.75)}
                        className="mx-auto w-full max-w-lg rounded-lg bg-white/5 p-10 shadow-card xs:p-6 xs:pt-5"
                        >

                        <div className='px-4 sm:pt-2 pb-4'>

                          <h2 className="text-3xl text-right font-bold tracking-tight text-white">
                            <span className="block">My Summary</span>
                          </h2>
                          <p className="mt-4 text-lg text-right leading-6 text-indigo-200">
                          personal metric of all combined vaults
                          </p>
                        </div>
                        {userMetrics.length < 2 ? (
                          <Loader />
                          ) : (
                            <>
                            <dl className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                              {userMetrics.map((metric, index) => (
                                <UserMetricsRenderer key={index} metric={metric} />
                                ))}
                            </dl>
                          </>
                        )}
                      </motion.div>

                    </div>
                  </div>
                        </motion.div>

              </div>
            </div>

          </div>
        </motion.div>
      </section>

    </>

  )
}

export default VaultMetrics