import PoolsDisplay from "../../components/app/PoolsDisplay"
import StatsCards from '../../components/app/StatsCards'
import PoolsNews from '../../components/app/PoolsNews'
import TreasuryCard from '../../components/app/TreasuryCard'

const Pools = ({data}) => {
    const availablePools = [
        {
            name: "Usdt",
            infos: "Safe Strategy",
            ibTokenAddress: "0x0",
            tvl: "100'000",
            image: ""
        },
        {
            asset: "Dai",
            ibTokenAddress: "0x0",
            tvl: "0",
        }
    ]
    const stats = [
        { name: 'Total Deposit', stat: 'N/a' },
        { name: 'Total Claimable', stat: 'N/a' },
        { name: 'Total Earned', stat: 'N/a' },
        { name: 'Actual Deepfi Balance', stat: 'N/a' }
    ]

    const treasury = [
        { name: 'MMY', stat: 'N/a', src:"https://s2.coinmarketcap.com/static/img/coins/64x64/23038.png" },
        { name: 'X', stat: 'N/a' },
        // { name: 'Total Earned', stat: 'N/a' },
        // { name: 'Actual Deepfi Balance', stat: 'N/a' }
    ]
    return (
        <div className="flex flex-col items-center">
            <div className="sm:w-3/4">
            <PoolsNews />
            {/* <div className="hidden sm:block">
                <h3 className="pb-2 text-xl font-semibold text-white">My Summary</h3>
                <StatsCards stats={stats} />
            </div> */}
            {/* <div className="sm:hidden"> */}
            {/* <div className="flex flex-col"> */}
            <h3 className="pt-4 text-xl font-semibold text-white text-center">Protocol Treasury</h3>
            <p className="mt-2 pb-4  text-sm text-gray-300 text-center">
                liquidity generated by the protocol
                    </p>
            <TreasuryCard stats={treasury} />

                <h3 className="pt-4 text-xl font-semibold text-white text-center">My Summary</h3>
                <p className="mt-2 pb-4 text-sm text-gray-300 text-center">
                        All pools combined
                    </p>
                <StatsCards stats={stats} />
            {/* </div> */}
            <PoolsDisplay availablePools={availablePools} setModaleConnectStatus={data} />
                </div>
        </div>
    )
}

export default Pools